# SerpAPI Search Module
# This module handles Amazon product searches using SerpAPI

from serpapi import GoogleSearch
import os
from typing import List, Dict, Any

def search_amazon_products(queries: List[str], num_results: int = 25) -> List[Dict[str, Any]]:
    """
    Search Amazon for multiple product queries using SerpAPI
    
    Args:
        queries: List of search queries generated by Gemini
        num_results: Number of results to return per query (default: 25, max: 100)
        
    Returns:
        List of raw SerpAPI search results for each query
    """
    # Get API key from environment variables
    api_key = os.getenv("SERP_API_KEY")
    if not api_key:
        raise ValueError("SERP_API_KEY not found in environment variables")
    
    results = []
    
    for query in queries:
        try:
            # Set up SerpAPI parameters
            params = {
                "engine": "amazon",
                "k": query,
                "amazon_domain": "amazon.com",
                "num": num_results,  # Limit results to top N products
                "api_key": api_key
            }
            
            # Perform the search
            search = GoogleSearch(params)
            result = search.get_dict()
            
            # Store the raw result
            results.append({
                "query": query,
                "success": True,
                "raw_data": result
            })
            
        except Exception as e:
            # Handle failed searches
            results.append({
                "query": query,
                "success": False,
                "error": str(e),
                "raw_data": None
            })
    
    return results
